//------------------------------------------------------------------------------
// <auto-generated>
//	   This code was generated by a tool.
//	   Runtime Version:4.0.30319.42000
//
//	   Changes to this file may cause incorrect behavior and will be lost if
//	   the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace OCC.HSM.Model {
	using System.Xml.Serialization;
	
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://oxfordcc.co.uk/hsm-inputs")]
	[System.Xml.Serialization.XmlRootAttribute("inputs", Namespace="http://oxfordcc.co.uk/hsm-inputs", IsNullable=false)]
	public partial class InputsType {
		
		private HouseType housetypeField;
		
		private WallType walltypeField;
		
		private HouseAgeType houseageField;
		
		private HouseSizeOption1Type housesizeoption1Field;
		
		private HouseSizeOption2Type housesizeoption2Field;
		
		private RoofType rooftypeField;
		
		private GlazingType glazingField;
		
		private GasSupplyType gassupplyField;
		
		private OutsideSpace outsidespaceField;
		
		private CurrentHeatingType currentheatingsystemField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("house-type")]
		public HouseType housetype {
			get {
				return this.housetypeField;
			}
			set {
				this.housetypeField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("wall-type")]
		public WallType walltype {
			get {
				return this.walltypeField;
			}
			set {
				this.walltypeField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("house-age")]
		public HouseAgeType houseage {
			get {
				return this.houseageField;
			}
			set {
				this.houseageField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("house-size-option1")]
		public HouseSizeOption1Type housesizeoption1 {
			get {
				return this.housesizeoption1Field;
			}
			set {
				this.housesizeoption1Field = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("house-size-option2")]
		public HouseSizeOption2Type housesizeoption2 {
			get {
				return this.housesizeoption2Field;
			}
			set {
				this.housesizeoption2Field = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("roof-type")]
		public RoofType rooftype {
			get {
				return this.rooftypeField;
			}
			set {
				this.rooftypeField = value;
			}
		}
		
		/// <remarks/>
		public GlazingType glazing {
			get {
				return this.glazingField;
			}
			set {
				this.glazingField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("gas-supply")]
		public GasSupplyType gassupply {
			get {
				return this.gassupplyField;
			}
			set {
				this.gassupplyField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("outside-space")]
		public OutsideSpace outsidespace {
			get {
				return this.outsidespaceField;
			}
			set {
				this.outsidespaceField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("current-heating-system")]
		public CurrentHeatingType currentheatingsystem {
			get {
				return this.currentheatingsystemField;
			}
			set {
				this.currentheatingsystemField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://oxfordcc.co.uk/hsm-inputs")]
	public partial class HouseType {
		
		private AnswerType[] answerField;
		
		private string explanationField;
		
		private string questionField;
		
		private string bctextField;
		
		private bool optionalField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("answer")]
		public AnswerType[] answer {
			get {
				return this.answerField;
			}
			set {
				this.answerField = value;
			}
		}
		
		/// <remarks/>
		public string explanation {
			get {
				return this.explanationField;
			}
			set {
				this.explanationField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string question {
			get {
				return this.questionField;
			}
			set {
				this.questionField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string bctext {
			get {
				return this.bctextField;
			}
			set {
				this.bctextField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public bool optional {
			get {
				return this.optionalField;
			}
			set {
				this.optionalField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://oxfordcc.co.uk/hsm-inputs")]
	public partial class AnswerType {
		
		private string usertextField;
		
		private CertificateMatchType[] certificatematchField;
		
		private string descriptionField;
		
		private string keyField;
		
		private short dbencodingField;
		
		/// <remarks/>
		public string usertext {
			get {
				return this.usertextField;
			}
			set {
				this.usertextField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("certificate-match")]
		public CertificateMatchType[] certificatematch {
			get {
				return this.certificatematchField;
			}
			set {
				this.certificatematchField = value;
			}
		}
		
		/// <remarks/>
		public string description {
			get {
				return this.descriptionField;
			}
			set {
				this.descriptionField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string key {
			get {
				return this.keyField;
			}
			set {
				this.keyField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public short dbencoding {
			get {
				return this.dbencodingField;
			}
			set {
				this.dbencodingField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://oxfordcc.co.uk/hsm-inputs")]
	public partial class CertificateMatchType {
		
		private string[] epctextField;
		
		private string epckeyField;
		
		private EPCMatchType matchtypeField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("epc-text")]
		public string[] epctext {
			get {
				return this.epctextField;
			}
			set {
				this.epctextField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute("epc-key")]
		public string epckey {
			get {
				return this.epckeyField;
			}
			set {
				this.epckeyField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute("match-type")]
		public EPCMatchType matchtype {
			get {
				return this.matchtypeField;
			}
			set {
				this.matchtypeField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://oxfordcc.co.uk/hsm-inputs")]
	public enum EPCMatchType {
		
		/// <remarks/>
		exact,
		
		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("integer-in-range")]
		integerinrange,
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://oxfordcc.co.uk/hsm-inputs")]
	public partial class CurrentHeatingType {
		
		private AnswerType[] answerField;
		
		private string explanationField;
		
		private string questionField;
		
		private string bctextField;
		
		private bool optionalField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("answer")]
		public AnswerType[] answer {
			get {
				return this.answerField;
			}
			set {
				this.answerField = value;
			}
		}
		
		/// <remarks/>
		public string explanation {
			get {
				return this.explanationField;
			}
			set {
				this.explanationField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string question {
			get {
				return this.questionField;
			}
			set {
				this.questionField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string bctext {
			get {
				return this.bctextField;
			}
			set {
				this.bctextField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public bool optional {
			get {
				return this.optionalField;
			}
			set {
				this.optionalField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://oxfordcc.co.uk/hsm-inputs")]
	public partial class OutsideSpace {
		
		private AnswerType[] answerField;
		
		private string explanationField;
		
		private string questionField;
		
		private string bctextField;
		
		private bool optionalField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("answer")]
		public AnswerType[] answer {
			get {
				return this.answerField;
			}
			set {
				this.answerField = value;
			}
		}
		
		/// <remarks/>
		public string explanation {
			get {
				return this.explanationField;
			}
			set {
				this.explanationField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string question {
			get {
				return this.questionField;
			}
			set {
				this.questionField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string bctext {
			get {
				return this.bctextField;
			}
			set {
				this.bctextField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public bool optional {
			get {
				return this.optionalField;
			}
			set {
				this.optionalField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://oxfordcc.co.uk/hsm-inputs")]
	public partial class GasSupplyType {
		
		private AnswerType[] answerField;
		
		private string explanationField;
		
		private string questionField;
		
		private string bctextField;
		
		private bool optionalField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("answer")]
		public AnswerType[] answer {
			get {
				return this.answerField;
			}
			set {
				this.answerField = value;
			}
		}
		
		/// <remarks/>
		public string explanation {
			get {
				return this.explanationField;
			}
			set {
				this.explanationField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string question {
			get {
				return this.questionField;
			}
			set {
				this.questionField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string bctext {
			get {
				return this.bctextField;
			}
			set {
				this.bctextField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public bool optional {
			get {
				return this.optionalField;
			}
			set {
				this.optionalField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://oxfordcc.co.uk/hsm-inputs")]
	public partial class GlazingType {
		
		private AnswerType[] answerField;
		
		private string explanationField;
		
		private string questionField;
		
		private string bctextField;
		
		private bool optionalField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("answer")]
		public AnswerType[] answer {
			get {
				return this.answerField;
			}
			set {
				this.answerField = value;
			}
		}
		
		/// <remarks/>
		public string explanation {
			get {
				return this.explanationField;
			}
			set {
				this.explanationField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string question {
			get {
				return this.questionField;
			}
			set {
				this.questionField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string bctext {
			get {
				return this.bctextField;
			}
			set {
				this.bctextField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public bool optional {
			get {
				return this.optionalField;
			}
			set {
				this.optionalField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://oxfordcc.co.uk/hsm-inputs")]
	public partial class RoofType {
		
		private AnswerType[] answerField;
		
		private string explanationField;
		
		private string questionField;
		
		private string bctextField;
		
		private bool optionalField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("answer")]
		public AnswerType[] answer {
			get {
				return this.answerField;
			}
			set {
				this.answerField = value;
			}
		}
		
		/// <remarks/>
		public string explanation {
			get {
				return this.explanationField;
			}
			set {
				this.explanationField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string question {
			get {
				return this.questionField;
			}
			set {
				this.questionField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string bctext {
			get {
				return this.bctextField;
			}
			set {
				this.bctextField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public bool optional {
			get {
				return this.optionalField;
			}
			set {
				this.optionalField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://oxfordcc.co.uk/hsm-inputs")]
	public partial class HouseSizeOption2Type {
		
		private AnswerType[] answerField;
		
		private string explanationField;
		
		private string questionField;
		
		private string bctextField;
		
		private bool optionalField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("answer")]
		public AnswerType[] answer {
			get {
				return this.answerField;
			}
			set {
				this.answerField = value;
			}
		}
		
		/// <remarks/>
		public string explanation {
			get {
				return this.explanationField;
			}
			set {
				this.explanationField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string question {
			get {
				return this.questionField;
			}
			set {
				this.questionField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string bctext {
			get {
				return this.bctextField;
			}
			set {
				this.bctextField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public bool optional {
			get {
				return this.optionalField;
			}
			set {
				this.optionalField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://oxfordcc.co.uk/hsm-inputs")]
	public partial class HouseSizeOption1Type {
		
		private AnswerType[] answerField;
		
		private string explanationField;
		
		private string questionField;
		
		private string bctextField;
		
		private bool optionalField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("answer")]
		public AnswerType[] answer {
			get {
				return this.answerField;
			}
			set {
				this.answerField = value;
			}
		}
		
		/// <remarks/>
		public string explanation {
			get {
				return this.explanationField;
			}
			set {
				this.explanationField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string question {
			get {
				return this.questionField;
			}
			set {
				this.questionField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string bctext {
			get {
				return this.bctextField;
			}
			set {
				this.bctextField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public bool optional {
			get {
				return this.optionalField;
			}
			set {
				this.optionalField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://oxfordcc.co.uk/hsm-inputs")]
	public partial class HouseAgeType {
		
		private AnswerType[] answerField;
		
		private string explanationField;
		
		private string questionField;
		
		private string bctextField;
		
		private bool optionalField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("answer")]
		public AnswerType[] answer {
			get {
				return this.answerField;
			}
			set {
				this.answerField = value;
			}
		}
		
		/// <remarks/>
		public string explanation {
			get {
				return this.explanationField;
			}
			set {
				this.explanationField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string question {
			get {
				return this.questionField;
			}
			set {
				this.questionField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string bctext {
			get {
				return this.bctextField;
			}
			set {
				this.bctextField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public bool optional {
			get {
				return this.optionalField;
			}
			set {
				this.optionalField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://oxfordcc.co.uk/hsm-inputs")]
	public partial class WallType {
		
		private AnswerType[] answerField;
		
		private string explanationField;
		
		private string questionField;
		
		private string bctextField;
		
		private bool optionalField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("answer")]
		public AnswerType[] answer {
			get {
				return this.answerField;
			}
			set {
				this.answerField = value;
			}
		}
		
		/// <remarks/>
		public string explanation {
			get {
				return this.explanationField;
			}
			set {
				this.explanationField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string question {
			get {
				return this.questionField;
			}
			set {
				this.questionField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string bctext {
			get {
				return this.bctextField;
			}
			set {
				this.bctextField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public bool optional {
			get {
				return this.optionalField;
			}
			set {
				this.optionalField = value;
			}
		}
	}
}
